export const LOGIN = 'LOGIN';

export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_SUCCESSFUL = 'REQUEST_SUCCESSFUL';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const EXP_REQUEST_STARTED = 'EXP_REQUEST_STARTED';
export const EXP_REQUEST_SUCCESSFUL = 'EXP_REQUEST_SUCCESSFUL';
export const EXP_REQUEST_FAILED = 'EXP_REQUEST_FAILED';

export const EXPENSES = 'EXPENSES';
export const REDUCEEX = 'REDUCEEX';
